# Generated by Django 3.1.2 on 2020-10-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_order', '0005_auto_20201026_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='quality_wraped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
