# Generated by Django 3.1.2 on 2020-11-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_order', '0006_order_detail_quality_wraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product1',
            field=models.FileField(blank=True, upload_to='image_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_product2',
            field=models.FileField(blank=True, upload_to='image_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_product3',
            field=models.FileField(blank=True, upload_to='image_product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_product4',
            field=models.FileField(blank=True, upload_to='image_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.FileField(blank=True, upload_to='image_product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
