# Generated by Django 3.1.3 on 2020-12-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_order', '0007_auto_20201104_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
