# Generated by Django 3.1.3 on 2021-01-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_order', '0008_remove_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='product_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
